# This workflow will build a Java project with Gradle
# For more information see: 
# https://help.github.com/actions/language-and-framework-guides
# /building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2
    #- name: Set up JDK 11
    #  uses: actions/setup-java@v1
    #  with:
    #    java-version: '11' # The JDK version to make available on the path.
    #    java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
    #    architecture: x64 # (x64 or x86) - defaults to x64
    #- name: Grant execute permission for gradlew
    #  run: chmod +x gradlew
    #- name: Run with Gradle
    #  run: ./gradlew bootrun &
    - name: ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.4.0
#     uses: zaproxy/action-api-scan@v0.1.1
      with:
        docker_name: 'owasp/zap2docker-stable'
        target: 'https://api.nonfunctionaltest.can4l.com/graphql'
        cmd_options: '-a -d -n set-apilist.context'
         

#    - name: ZAP Full Scan1
#      uses: zaproxy/action-full-scan@v0.4.0
#      uses: zaproxy/action-api-scan@v0.1.1
#      with:
#        docker_name: 'owasp/zap2docker-stable'
#        target: 'https://api.nonfunctionaltest.can4l.com/ngsi-ld/v1/entityOperations/create'
#        cmd_options: '-a -d -n 20220727.context'
        
    - name: ZAP Full Scan2
      uses: zaproxy/action-full-scan@v0.4.0
      uses: zaproxy/action-api-scan@v0.1.1
      with:
        docker_name: 'owasp/zap2docker-stable'
        target: 'https://api.nonfunctionaltest.can4l.com/ngsi-ld/v1/entities/?type=WaterLevel&q=refPointOfInterest==%22urn:ngsi-ld:Spot:id:02%22'
        cmd_options: '-a -d -n 20220727.context'
        
#    - name: ZAP Full Scan3
#      uses: zaproxy/action-full-scan@v0.4.0
#      uses: zaproxy/action-api-scan@v0.1.1
#      with:
#        docker_name: 'owasp/zap2docker-stable'
#        target: 'https://api.nonfunctionaltest.can4l.com/ngsi-ld/v1/entities/urn:ngsi-ld:WaterLevel:2485-08-20T23:07:06.00Z/attrs/streamGauge'
#        cmd_options: '-a -d -n 20220727.context'
        
#    - name: ZAP Full Scan4
#      uses: zaproxy/action-full-scan@v0.4.0
#      uses: zaproxy/action-api-scan@v0.1.1
#      with:
#        docker_name: 'owasp/zap2docker-stable'
#        target: 'https://api.nonfunctionaltest.can4l.com/ngsi-ld/v1/entities/?type=WeatherForecast'
#        cmd_options: '-a -d -n 20220727.context'
